version: '2'
services:
  web:
    image: "moody"
    volumes:
     - .:/mrmoody-data
    links:
     - influx
  influx:
    image: "influxdb:1.1"
    ports:
     - "8086"
  grafana:
    image: "grafana/grafana"
    ports:
     - "3000:3000"
    links:
     - influx